routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/login', 'Auth\AdminAuthController@getLogin')->name('admin.login');
Route::post('admin/login', 'Auth\AdminAuthController@postLogin')->name("admin.login.post");
Route::get('admin/logout', 'Auth\AdminAuthController@postLogout')->name("admin.logout");

Auth::routes([
    'reset' => false,
    'verify' => false,
]);

// Route untuk user

Route::group(["middleware" => "auth"], function() {
    Route::get('/home', 'HomeController@index')->name('user.home');
    Route::get('/user/profile/{user}', 'HomeController@userProfile')->name('user.profile');
    Route::get('/user/profile/edit/{user}', 'HomeController@editUserProfile')->name('user.profile.edit');
    Route::put('/user/profile/update/{user}', 'HomeController@updateUserProfile')->name('user.profile.update');

    Route::resource("reports", "ReportController", ["as" => "user"])->except(["show", "edit", "update", "destroy"]);
});

// Route untuk admin

Route::group(["prefix" => "admin", "middleware" => "auth:admin"], function() {
    Route::get("/home", function() {
        return view("admin.index");
    })->name("admin.home");

    Route::resource("jobs", "JobController", ["as" => "admin"])->except(["show"]);
    Route::resource("provinces", "ProvinceController", ["as" => "admin"])->except(["show"]);
    Route::resource("cities", "CityController", ["as" => "admin"])->except(["show"]);
    Route::resource("users", "UserController", ["as" => "admin"])->except(["show", "create", "store", "edit", "update"]);
    Route::resource("reports", "UserReportController", ["as" => "admin"])->except(["create", "store", "edit", "update", "destroy"]);
});

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
    protected $fillable = ["name"];

    public function users() {
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/JobController.php
<?php

namespace App\Http\Controllers;

use App\Job;
use Illuminate\Http\Request;

class JobController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $jobs = Job::orderBy("created_at", "DESC")->paginate(10);
        
        return view("admin.jobs.index", compact("jobs"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("admin.jobs.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            "name" => "required"
        ]);

        Job::create($request->except("_token"));

        return redirect(route("admin.jobs.index"))->with(["success" => "Pekerjaan berhasil ditambahkan!"]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Job  $job
     * @return \Illuminate\Http\Response
     */
    public function edit(Job $job)
    {
        return view("admin.jobs.edit", compact("job"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Job  $job
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Job $job)
    {
        $this->validate($request, [
            "name" => "required"
        ]);

        $job->update($request->except("_token"));

        return redirect(route("admin.jobs.index"))->with(["success" => "Pekerjaan berhasil diupdate!"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Job  $job
     * @return \Illuminate\Http\Response
     */
    public function destroy(Job $job)
    {
        $selectedJob = Job::with(["users"])->where("id", $job->id)->first();

        if (count($selectedJob->users) > 0) {
            return redirect(route("admin.jobs.index"))->with(["error" => "Pekerjaan sedang digunakan!"]);
        }

        $job->delete();

        return redirect(route("admin.jobs.index"))->with(["success" => "Pekerjaan berhasil dihapus!"]);
    }
}

resources/views/admin/jobs/create.blade.php
@extends('layouts.admin_template')

@section('title')
<title>Tambah Pekerjaan</title>
@endsection

@section('content-title')
<h1>Tambah Pekerjaan</h1>
@endsection

@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form action="{{ route('admin.jobs.store') }}" method="POST">
                    @csrf

                    <div class="form-group">
                        <label>Nama Pekerjaan</label>

                        <input name="name" type="text" class="form-control" id="name"
                            placeholder="Masukkan nama pekerjaan">

                        <p class="text-danger">{{ $errors->first("name") }}</p>
                    </div>

                    <button class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/jobs/edit.blade.php
@extends('layouts.admin_template')

@section('title')
<title>Edit Pekerjaan</title>
@endsection

@section('content-title')
<h1>Edit Pekerjaan</h1>
@endsection

@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form action="{{ route('admin.jobs.update', $job->id) }}" method="POST">
                    @csrf
                    @method("PUT")

                    <div class="form-group">
                        <label>Nama Pekerjaan</label>

                        <input name="name" type="text" class="form-control" id="name"
                            placeholder="Masukkan nama pekerjaan" value="{{ $job->name }}">

                        <p class="text-danger">{{ $errors->first("name") }}</p>
                    </div>

                    <button class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/jobs/index.blade.php
@extends('layouts.admin_template')

@section('title')
<title>Manajemen Pekerjaan</title>
@endsection

@section('content-title')
<h1>Manajemen Pekerjaan</h1>
@endsection

@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                @if (session("success"))
                <div class="alert alert-success alert-dismissible show fade">
                    <div class="alert-body">
                        <button class="close" data-dismiss="alert">
                            <span>×</span>
                        </button>

                        {{ session("success") }}
                    </div>
                </div>
                @endif

                @if (session("error"))
                <div class="alert alert-danger alert-dismissible show fade">
                    <div class="alert-body">
                        <button class="close" data-dismiss="alert">
                            <span>×</span>
                        </button>

                        {{ session("error") }}
                    </div>
                </div>
                @endif

                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nama Pekerjaan</th>
                            <th scope="col">Aksi</th>
                        </tr>
                    </thead>

                    <tbody>
                        @forelse ($jobs as $job)
                        <tr>
                            <th scope="row">{{ $loop->iteration }}</th>
                            <td>{{ $job->name }}</td>
                            <td>
                                <form action="{{ route('admin.jobs.destroy', $job->id) }}" method="POST">
                                    @csrf
                                    @method("DELETE")

                                    <a href="{{ route('admin.jobs.edit', $job->id) }}"
                                        class="btn btn-sm btn-warning">Edit</a>

                                    <button class="btn btn-sm btn-danger">Hapus</button>
                                </form>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="3" class="text-center">Tidak ada pekerjaan ...</td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>

                {{ $jobs->links() }}
            </div>
        </div>
    </div>
</div>
@endsection