routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/login', 'Auth\AdminAuthController@getLogin')->name('admin.login');
Route::post('admin/login', 'Auth\AdminAuthController@postLogin')->name("admin.login.post");
Route::get('admin/logout', 'Auth\AdminAuthController@postLogout')->name("admin.logout");

Auth::routes([
    'reset' => false,
    'verify' => false,
]);

// Route untuk user

Route::group(["middleware" => "auth"], function() {
    Route::get('/home', 'HomeController@index')->name('user.home');
    Route::get('/user/profile/{user}', 'HomeController@userProfile')->name('user.profile');
    Route::get('/user/profile/edit/{user}', 'HomeController@editUserProfile')->name('user.profile.edit');
    Route::put('/user/profile/update/{user}', 'HomeController@updateUserProfile')->name('user.profile.update');

    Route::resource("reports", "ReportController", ["as" => "user"])->except(["show", "edit", "update", "destroy"]);
});

// Route untuk admin

Route::group(["prefix" => "admin", "middleware" => "auth:admin"], function() {
    Route::get("/home", function() {
        return view("admin.index");
    })->name("admin.home");

    Route::resource("jobs", "JobController", ["as" => "admin"])->except(["show"]);
    Route::resource("provinces", "ProvinceController", ["as" => "admin"])->except(["show"]);
    Route::resource("cities", "CityController", ["as" => "admin"])->except(["show"]);
    Route::resource("users", "UserController", ["as" => "admin"])->except(["show", "create", "store", "edit", "update"]);
    Route::resource("reports", "UserReportController", ["as" => "admin"])->except(["create", "store", "edit", "update", "destroy"]);
});

resources/views/layouts/user_module/footer.blade.php
<footer class="main-footer">
    <p class="text-center">&copy; 2020. All Rights Reserved.</p>
</footer>

resources/views/layouts/user_module/navbar.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
        </ul>
    </form>

    <ul class="navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <img alt="image" src="{{ asset('assets/images/' . Auth::user()->image) }}" class="rounded-circle mr-1">
                <div class="d-sm-none d-lg-inline-block">{{ Auth::user()->name }}</div>
            </a>

            <div class="dropdown-menu dropdown-menu-right">
                <a href="{{ route('user.profile', Auth::user()->id) }}" class="dropdown-item has-icon">
                    <i class="far fa-user"></i> Profile
                </a>

                <a class="dropdown-item has-icon text-danger" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/user_module/sidebar.blade.php
<div class="main-sidebar sidebar-style-2">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="{{ route('user.home') }}">Data Warga</a>
        </div>

        <div class="sidebar-brand sidebar-brand-sm">
            <a href="{{ route('user.home') }}">DW</a>
        </div>

        <ul class="sidebar-menu">
            <li class="dropdown">
                <a href="{{ route('user.home') }}" class="nav-link"><i
                        class="fas fa-fire"></i><span>Dashboard</span></a>
            </li>

            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fa fa-envelope"></i><span>Laporan Mandiri</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('user.reports.create') }}">Buat Laporan</a></li>
                    <li><a class="nav-link" href="{{ route('user.reports.index') }}">Riwayat
                            Laporan</a></li>
                </ul>
            </li>
        </ul>
    </aside>
</div>